SHOW CREATE TABLE `dev`.`cargaHoraria`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `cargaHoraria`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='cargaHoraria' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `cargaHoraria` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='cargaHoraria'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='cargaHoraria'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`cargaHoraria`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);

SHOW CREATE TABLE `dev`.`cargaHorario`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `cargaHorario`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='cargaHorario' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `cargaHorario` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='cargaHorario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='cargaHorario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`cargaHorario`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);

SHOW CREATE TABLE `dev`.`horario`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `horario`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='horario' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `horario` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='horario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='horario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`horario`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);

SHOW CREATE TABLE `dev`.`periodos`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `periodos`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='periodos' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `periodos` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='periodos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='periodos'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`periodos`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);

SHOW CREATE TABLE `dev`.`politica`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `politica`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='politica' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `politica` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='politica'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='politica'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`politica`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);

SHOW CREATE TABLE `dev`.`politicaHorario`;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
TRUNCATE `politicaHorario`;
SHOW DATABASES;
SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`='dev';
SHOW TABLE STATUS FROM `dev`;
SHOW FUNCTION STATUS WHERE `Db`='dev';
SHOW PROCEDURE STATUS WHERE `Db`='dev';
SHOW TRIGGERS FROM `dev`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`='dev';
SELECT * FROM `information_schema`.`COLUMNS` WHERE TABLE_SCHEMA='dev' AND TABLE_NAME='politicaHorario' ORDER BY ORDINAL_POSITION;
SHOW INDEXES FROM `politicaHorario` FROM `dev`;
SELECT * FROM information_schema.REFERENTIAL_CONSTRAINTS WHERE   CONSTRAINT_SCHEMA='dev'   AND TABLE_NAME='politicaHorario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE   TABLE_SCHEMA='dev'   AND TABLE_NAME='politicaHorario'   AND REFERENCED_TABLE_NAME IS NOT NULL;
SHOW CREATE TABLE `dev`.`politicaHorario`;
/* Entrando na sessão "admin" */
SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1);



